SRC_OUTPUT_VPS_PATHNAME:=/tmp
OUTPUT_LOCAL_PATHNAME:=/tmp/web
SRC_OUTPUT_LOCAL_PATHNAME:=$(OUTPUT_LOCAL_PATHNAME)/html
BLOG_SRC_INPUT_LOCAL_PATHNAME:=src/blog
BLOG_SRC_OUTPUT_LOCAL_PATHNAME:=$(SRC_OUTPUT_LOCAL_PATHNAME)/blog
CSS_BLOG_SRC_OUTPUT_LOCAL_PATHNAME:=$(SRC_OUTPUT_LOCAL_PATHNAME)/blog.css
WIKI_SRC_INPUT_LOCAL_PATHNAME:=src/wiki
WIKI_SRC_OUTPUT_LOCAL_PATHNAME:=$(SRC_OUTPUT_LOCAL_PATHNAME)/wiki
PANDOC_CONFIG_OUTPUT_LOCAL_PATHNAME:=$(OUTPUT_LOCAL_PATHNAME)/pandoc-config
PANDOC_TEMPLATE_OUTPUT_LOCAL_PATHNAME:=$(PANDOC_CONFIG_OUTPUT_LOCAL_PATHNAME)/template.html
PANDOC_METADATA_OUTPUT_LOCAL_PATHNAME:=$(PANDOC_CONFIG_OUTPUT_LOCAL_PATHNAME)/metadata.yml

create-web:
	rm -rf $(OUTPUT_LOCAL_PATHNAME)
	mkdir $(OUTPUT_LOCAL_PATHNAME)
	mkdir $(SRC_OUTPUT_LOCAL_PATHNAME)
	mkdir $(BLOG_SRC_OUTPUT_LOCAL_PATHNAME)
	mkdir $(WIKI_SRC_OUTPUT_LOCAL_PATHNAME)
	mkdir $(PANDOC_CONFIG_OUTPUT_LOCAL_PATHNAME)
	cp pandoc-config/* $(PANDOC_CONFIG_OUTPUT_LOCAL_PATHNAME)/
	cp -r src/felices-fiestas $(SRC_OUTPUT_LOCAL_PATHNAME)
	cp src/avatar.png $(SRC_OUTPUT_LOCAL_PATHNAME)
	cp src/blog/blog.css $(CSS_BLOG_SRC_OUTPUT_LOCAL_PATHNAME)
	cp src/favicon.ico $(SRC_OUTPUT_LOCAL_PATHNAME)
	cp src/index.css $(SRC_OUTPUT_LOCAL_PATHNAME)
	cp src/index.html $(SRC_OUTPUT_LOCAL_PATHNAME)
	cp src/robots.txt $(SRC_OUTPUT_LOCAL_PATHNAME)
	./convert-md-to-html $(BLOG_SRC_INPUT_LOCAL_PATHNAME)/2021-05-15-leer-periodicos-online-sin-iniciar-sesion.md $(BLOG_SRC_OUTPUT_LOCAL_PATHNAME)/2021-05-15-leer-periodicos-online-sin-iniciar-sesion.html $(CSS_BLOG_SRC_OUTPUT_LOCAL_PATHNAME) $(PANDOC_TEMPLATE_OUTPUT_LOCAL_PATHNAME) $(PANDOC_METADATA_OUTPUT_LOCAL_PATHNAME)
	./convert-md-to-html $(BLOG_SRC_INPUT_LOCAL_PATHNAME)/2021-09-12-utilizar-protonmail-con-tor-y-no-con-protonvpn.md $(BLOG_SRC_OUTPUT_LOCAL_PATHNAME)/2021-09-12-utilizar-protonmail-con-tor-y-no-con-protonvpn.html $(CSS_BLOG_SRC_OUTPUT_LOCAL_PATHNAME) $(PANDOC_TEMPLATE_OUTPUT_LOCAL_PATHNAME) $(PANDOC_METADATA_OUTPUT_LOCAL_PATHNAME)
	./convert-md-to-html $(WIKI_SRC_INPUT_LOCAL_PATHNAME)/ssh.md $(WIKI_SRC_OUTPUT_LOCAL_PATHNAME)/ssh.html $(CSS_BLOG_SRC_OUTPUT_LOCAL_PATHNAME) $(PANDOC_TEMPLATE_OUTPUT_LOCAL_PATHNAME) $(PANDOC_METADATA_OUTPUT_LOCAL_PATHNAME)
	rm -rf $(PANDOC_CONFIG_OUTPUT_LOCAL_PATHNAME)

send-files:
	scp -P $(VPS_DEV_PORT) -r $(SRC_OUTPUT_LOCAL_PATHNAME)/ $(VPS_DEV_USER)@$(VPS_DEV_IP):$(SRC_OUTPUT_VPS_PATHNAME)/

open-html:
	firefox $(SRC_OUTPUT_LOCAL_PATHNAME)/index.html

test: create-web open-html

deploy: create-web send-files

export-template-html:
	# https://pandoc.org/MANUAL.html#option--print-default-template
	pandoc -D html > /tmp/template-default.html
