#!/bin/bash

set -e # Exit if any command fails.

main_project_pathname=$1

wiki_repository_name=wiki
wiki_content_pathname=$main_project_pathname/src/$wiki_repository_name
if [ -d ${wiki_content_pathname} ]; then
  echo "[DEBUG] Deleting old wiki content pathname ${wiki_content_pathname}"
  rm -rf ${wiki_content_pathname}
fi
echo "[DEBUG] Cloning wiki content"
git clone --depth=1 --branch=main https://github.com/CarlosAMolina/${wiki_repository_name} /tmp/${wiki_repository_name}
echo "[DEBUG] Moving cloned wiki files to the current repository"
mv /tmp/${wiki_repository_name}/src ${wiki_content_pathname}
echo "[DEBUG] Deleting cloned wiki repository"
rm -rf /tmp/${wiki_repository_name}
