#!/bin/bash

volume_name_nginx_web_content=$1

volume_web_content_pathname=$(/bin/bash get-docker-volume-pathname "${volume_name_nginx_web_content}")
volume_tools_pathname=$volume_web_content_pathname/tools/
echo "[DEBUG] Init clone tools in $volume_tools_pathname"
cd $volume_tools_pathname
rm -rf open-urls
git clone --depth=1 --branch=main https://github.com/CarlosAMolina/open-urls
rm -rf open-urls/.git
rm -rf job-check-lambda-name
git clone --depth=1 --branch=main https://github.com/CarlosAMolina/job-check-lambda-name
rm -rf job-check-lambda-name/.git

