#!/bin/bash

docker_pandoc_image_name=$1
docker_python_image_name=$2
docker_volume_name_nginx_web_content=$3
docker_volume_name_pandoc=$4

echo "[DEBUG] Init create-pandoc-script-for-files"
make -f makefile-create-pandoc-script-for-files \
	run \
	DOCKER_IMAGE_NAME=${docker_python_image_name} \
	DOCKER_VOLUME_NGINX_WEB_CONTENT=${docker_volume_name_nginx_web_content} \
	DOCKER_VOLUME_PANDOC=${docker_volume_name_pandoc}

echo "[DEBUG] Init make script executable"
volume_pandoc_pathname=$(docker volume inspect "${docker_volume_name_pandoc}" --format '{{.Mountpoint}}')
script_pathname=${volume_pandoc_pathname}/run-on-files-convert-md-to-html
until [ -f ${script_pathname} ]
do
    echo "[DEBUG] The file ${script_pathname} does not exist. Retrying again"
    sleep 2
done
chmod +x ${script_pathname}

echo "[DEBUG] Init makefile-convert-md-to-html-for-files"
make -f makefile-convert-md-to-html-for-files \
	run \
	DOCKER_IMAGE_NAME=${docker_pandoc_image_name} \
	DOCKER_VOLUME_NGINX_WEB_CONTENT=${docker_volume_name_nginx_web_content} \
	DOCKER_VOLUME_PANDOC=${docker_volume_name_pandoc}
