#!/bin/bash

volume_name_nginx_web_content=$1
volume_name_pandoc=$2

# Pandoc
volume_pandoc_pathname=$(docker volume inspect "${volume_name_pandoc}" --format '{{.Mountpoint}}')
echo "[ÐEBUG] Init copy web content to $volume_pandoc_pathname"
cp -r pandoc-config $volume_pandoc_pathname
cp -r md-to-html $volume_pandoc_pathname
cp convert-md-to-html $volume_pandoc_pathname
cp create-pandoc-script-for-files $volume_pandoc_pathname

# Web content
volume_web_content_pathname=$(docker volume inspect "${volume_name_nginx_web_content}" --format '{{.Mountpoint}}')
echo "[ÐEBUG] Init copy web content to $volume_web_content_pathname"
cp -r ../src $volume_web_content_pathname
