#!/bin/bash

volume_name_nginx_web_content=$1
volume_name_pandoc=$2

echo "[DEBUG] Init create pandoc script"
python \
	/${volume_name_pandoc}/md-to-html/src/main.py \
	/${volume_name_nginx_web_content}/blog.css \
	/${volume_name_pandoc}/pandoc-config/metadata.yml \
	/${volume_name_pandoc}/convert-md-to-html \
	/${volume_name_pandoc}/pandoc-config/template.html \
	/${volume_name_nginx_web_content} \
	/${volume_name_pandoc}/run-on-files-convert-md-to-html
