# syntax=docker/dockerfile:1
FROM python:3.8.15-alpine3.16
ARG volume_nginx_web_content
ARG volume_pandoc
ENV volume_nginx_web_content=${volume_nginx_web_content}
ENV volume_pandoc=${volume_pandoc}
ENTRYPOINT /bin/sh /$volume_pandoc/create-pandoc-script-for-files $volume_nginx_web_content $volume_pandoc
#ENTRYPOINT ["tail", "-f", "/dev/null"]
