# syntax=docker/dockerfile:1
FROM pandoc/minimal:2.17-alpine
# TODO /pandoc as arg volume-pandoc
ENTRYPOINT ["/bin/sh", "/pandoc/run-on-files-convert-md-to-html"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]
