# syntax=docker/dockerfile:1
FROM python:3.8.15-alpine3.16
# TODO /pandoc as arg volume-pandoc
ENTRYPOINT ["/bin/sh", "/pandoc/create-pandoc-script-for-files"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]
