# syntax=docker/dockerfile:1
FROM python:3.8.15-alpine3.16
# TODO /pandoc as arg volume-pandoc, and "nginx-web-content" as arg too
ENTRYPOINT ["/bin/sh", "/pandoc/create-pandoc-script-for-files", "nginx-web-content", "pandoc"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]
