#!/bin/bash

url_nginx_localhost=$1
volume_name_nginx_web_content=$2

volume_nginx_web_content_pathname=$(docker volume inspect "${volume_name_nginx_web_content}" --format '{{.Mountpoint}}')
index_html_pathname=${volume_nginx_web_content_pathname}/index.html

echo "[DEBUG] Init open HTML"
until [ -f ${index_html_pathname} ]
do
    echo "[DEBUG] The file ${index_html_pathname} does not exist. Retrying again"
    sleep 2
done
firefox $url_nginx_localhost

