#!/bin/bash

#docker_volume_name_nginx_logs=$1
docker_volume_name_nginx_web_content=$1
docker_volume_name_pandoc=$2

remove_if_exists() {
  volume=$1
  echo "[DEBUG] Init remove volume ${volume}"
  if exists_volume ${volume}; then
    echo "[DEBUG] The volume exists. Init remove"
    docker volume rm ${volume}
    echo "[DEBUG] The volume has been removed"
  else
    echo "[DEBUG] The volume does not exist, no action is required"
  fi
}

exists_volume() {
  if docker volume ls | grep -q ${volume}; then
    return 0; # 0 = true
  else
    return 1; # 1 = false
  fi
}

#remove_if_exists ${docker_volume_name_nginx_logs}
remove_if_exists ${docker_volume_name_nginx_web_content}
remove_if_exists ${docker_volume_name_pandoc}

