#!/bin/bash

volume_name_nginx_web_content=$1
vps_src_output_pathname=$2

volume_nginx_web_content_pathname=$(/bin/bash get-docker-volume-pathname "${volume_name_nginx_web_content}")
html_directory_pathname=${volume_nginx_web_content_pathname}

echo "[DEBUG] Init send files to VPS"
echo "[DEBUG] Connection details:"
echo "[DEBUG] - VPS port: ${VPS_DEV_PORT}"
echo "[DEBUG] - VPS IP: ${VPS_DEV_IP}"
echo "[DEBUG] - VPS identity file: ${VPS_DEV_IDENTITY_FILE}"
echo "[DEBUG] - VPS output pathname: ${vps_src_output_pathname}"
echo "[DEBUG] - Local host files pathname: ${html_directory_pathname}"
scp -P ${VPS_DEV_PORT} \
	-i ${VPS_DEV_IDENTITY_FILE} \
	-r ${html_directory_pathname}/* \
	${VPS_DEV_USER}@${VPS_DEV_IP}:${vps_src_output_pathname}/

