#!/bin/bash

container=$1

stop_if_running() {
  container=$1
  echo "[DEBUG] Init stop container ${container}"
  if is_running ${container}; then
    echo "[DEBUG] The container is running. Init stop"
    docker stop ${container} || true
    if is_running ${container}; then
      echo "[ERROR] The container has not been stopped"
      exit 1
    else
      echo "[DEBUG] The container has been stopped"
    fi
  else
    echo "[DEBUG] The container is not running, no action is required"
  fi
}

is_running() {
  if docker ps | grep -q ${container}; then
    return 0; # 0 = true
  else
    return 1; # 1 = false
  fi
}

stop_if_running ${container}

