#!/bin/bash

echo "[DEBUG] Init check current git branch is updated"
if [ $(/bin/bash is-git-current-branch-updated) -eq 0 ]; then
    echo "[DEBUG] The current branch is updated"
else
    echo "[DEBUG] The current git branch is not updated"
    /bin/bash update-git-current-branch
    # If the main makefile file was updated in origin, 
    # its last version won't be used despite pulling it
    # because the old version is running.
    echo "[ERROR] The local branch was not updated. Remote changes have been downloaded. Please deploy again"
    exit 1
fi

