#!/bin/bash

container=$1

echo "[DEBUG] Init wait until container ${container} is stopped"
while [ $(/bin/bash is-container-running ${container}) -eq 0 ]
do
  echo "[DEBUG] Container ${container} is running. Init wait a few seconds"
  sleep 5
done
echo "[DEBUG] Container ${container} is stopped"

